### ISSUE TITLE
A2l file generation

### ISSUE THREAD

**Issue by 1059728589** [DanielT/a2ltool#25]
Hello Developer,
        May I ask if this tool supports generating a2l files? For example, generated through code or configuration files.

**Comment by DanielT** [comment]
Yes, you can create a2l files from the command line.

The README gives an example:

    Create a new a2lfile and add a characteristic from an elf file to it

    a2ltool --create --ellfile input.elf --characteristic my_var --output newfile.a2l

a2ltool does not have any configuration files. It reads and writes a2lfiles and can extract information from the debug data section of elf files.

**Comment by 1059728589** [comment]
![ed030a17-9daa-4dd8-8d7a-c4b920265bc8](https://github.com/DanielT/a2ltool/assets/166278990/29a8491d-81ee-408b-8dff-dee851be25fe)

Please ask two questions:
1. Can there be three ways to input and generate into a2l by inputting a single variable, a variable within an address range, or a wildcard?
2. Is the conversion method and other information accurate?

**Comment by DanielT** [comment]
1) yes that's correct
2) yes, the conversion information is accurate according to the debug information in the elf file. Regular values such as integers and floats are set to NO_COMPU_METHOD, while enums are associated with a COMPU_METHOD that describes the enum values

**Comment by 1059728589** [comment]
Thank you for the answer. I still have some questions
1、For the second question, as mentioned above, the one generated using a2ltool is NO-COMPU-METHOD, while my original one was Val_Wu8. And there is a FORMAT item present
2、Can the following function content be generated by SWC when using address ranges or wildcard characters
/begin FUNCTION
BO_SA_FDD_FrontWinHeatCtrl
"labels of the unit BO_SA_FDD_FrontWinHeatCtrl"
/begin IN_MEASUREMENT
/end IN_MEASUREMENT
/begin OUT_MEASUREMENT
/end OUT_MEASUREMENT
/begin LOC_MEASUREMENT
/end LOC_MEASUREMENT
/begin DEF_CHARACTERISTIC
/end FUNCTION

**Comment by DanielT** [comment]
1) It is possible, to associate a compu method with any MEASUREMENT or CHARACTERISTIC, but in all cases except enums a2ltool does not have enough information to create that.
Similary, you can define an output formatting using FORMAT, but how would a2ltool know of your preferences?

2) A2ltool does not create any FUNCTIONs.

You seem confused about the use case for a2ltool, so maybe this longer explanation can help you:

The core functionality of a2ltool is to merge and update existing a2l files created by other tools which have more complete information about the software structure and which can therefore generate better a2l files.

For example you might have:
- model based software development in something like TargetLink which generates C/C++ code and a2l
-  an AUTOSAR configuration which generates code and a matching a2l file
- a calibration management tool, which generates the code and the a2l file for calibration data.

A2ltool would then merge these separate inputs together and update the addresses of all the MEASUREMENTs and CHARACTERISTICs.

Using a2ltool to create an a2l file should only be considered if better inputs are not available, because a2ltool has less information available than other tools.

**Comment by 1059728589** [comment]
I understand now,
Thank you very much for your detailed answer.
I was originally looking for a core feature to create an a2l tool.
