### ISSUE TITLE
guideline

### ISSUE THREAD

**Issue by zoro9091** [DanielT/a2ltool#34]
could you please write a quick guideline how to use this package?
I know how to handle a2l files but I don't have any experience with rust packages.

Thanks for your effort.

**Comment by DanielT** [comment]
I'm not sure what problem you're having, so I'll just give a quick overview:

If you're using windows and just want to run a2ltool, then you can download the latest .zip file from the releases page.

It's capable of running on Linux and macOS too, but in that case you'll have to clone the source and compile it yourself.
You can follow the instructions on [rust-lang.org](https://www.rust-lang.org/learn/get-started) to get the Rust compiler, and after you have that you can run `cargo build --release` in the cloned source directory.

The tool itself is a command line tool. Nothing happens if you simply click on a2ltool.exe.

You have to run it in a terminal and provide command line arguments to make the tool modifiy or update your files.

The README.md of this repo has some examples. and like most command line tools, you can list all the options with `a2ltool --help`
