### ISSUE TITLE
Mixed line endings(LF and CRLF) in output file

### ISSUE THREAD

**Issue by Ahelion** [DanielT/a2ltool#7]
When updating an exiting a2l file generated with CANAPE, the resulting output file from the a2ltool ( -o option) has mixed line endings.
Would be nice to be normalized, either LF or CRLF, or allow the user to choose.

**Comment by DanielT** [comment]
At the moment, it's like this: all line endings are always LF.
The exception is all the text between "/begin A2ML" and "/end A2ML". This is directly copied from the input in order to preserve any comments, so that would also preserve any CRLF line endings in this block of text.

I would be interested to hear if my theory matches your observation, or if you have CRLF in any other place.

**Comment by Ahelion** [comment]
I did not investigate to deep, what I do is after I finish updating one a2l file, I copy it and using AWK  I modify the CAN ids ( 2 ecus ), and write to file (cmd operator > ), I saw that the resulting file is bigger then it should be, like 2K bigger.
Like I said, this is just cosmetic, no show stopper. The tool works properly, very happy with it.
Oh, and my PC died today, please expect a very delaied response till I get a new one or this one fixed.

**Comment by Ahelion** [comment]
Confirmed. only the block A2ML has CRLF, the rest are LF

**Comment by DanielT** [comment]
By the way, the release 1.2.0 which I tagged earlier fixes this, and the A2ML text will also only use LF line endings.
